"""Add marketplace payment QR

Revision ID: 057294278e8d
Revises: 7d79eba7ea88
Create Date: 2026-09-23 00:46:01.075374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057294278e8d'
down_revision = '7d79eba7ea88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_qrs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_qrs')
    # ### end Alembic commands ###
