"""add tag system

Revision ID: 081024102510
Revises: bf0b9aac52a9
Create Date: 2026-09-06 16:33:04.212464

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081024102510'
down_revision = 'bf0b9aac52a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create tags table
    op.create_table(
        'tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=80), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    # Add tag_id to collections
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'tag_id',
                sa.Integer(),
                nullable=True
            )
        )

        batch_op.create_foreign_key(
            'fk_collections_tag_id',
            'tags',
            ['tag_id'],
            ['id']
        )

        batch_op.drop_column('category')

    # Add tag information to submissions
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'tag_id',
                sa.Integer(),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'new_tag',
                sa.String(length=80),
                nullable=True
            )
        )

        batch_op.create_foreign_key(
            'fk_submissions_tag_id',
            'tags',
            ['tag_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove tag information from submissions
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_submissions_tag_id',
            type_='foreignkey'
        )

        batch_op.drop_column('new_tag')
        batch_op.drop_column('tag_id')

    # Restore category and remove tag_id from collections
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'category',
                sa.VARCHAR(length=80),
                nullable=True
            )
        )

        batch_op.drop_constraint(
            'fk_collections_tag_id',
            type_='foreignkey'
        )

        batch_op.drop_column('tag_id')

    # Remove tags table
    op.drop_table('tags')

    # ### end Alembic commands ###