"""Add payment and trade rejection reasons

Revision ID: 25363a185d18
Revises: 5b91626898c7
Create Date: 2026-09-26 01:26:30.134768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25363a185d18'
down_revision = '5b91626898c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')

    # ### end Alembic commands ###
