"""Add trade offered item image

Revision ID: 5b91626898c7
Revises: 70342a1fcdd2
Create Date: 2026-09-25 01:09:37.585338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b91626898c7'
down_revision = '70342a1fcdd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offered_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('offered_image')

    # ### end Alembic commands ###
