"""Add user ban fields

Revision ID: 6b1da5fd8a99
Revises: 57d582ec9efc
Create Date: 2026-09-20 21:54:16.886766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1da5fd8a99'
down_revision = '57d582ec9efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   with op.batch_alter_table('users', schema=None) as batch_op:
    batch_op.add_column(
        sa.Column(
            'is_banned',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )
    batch_op.add_column(
        sa.Column(
            'ban_reason',
            sa.Text(),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ban_reason')
        batch_op.drop_column('is_banned')

    # ### end Alembic commands ###
