"""Add trade offered item condition

Revision ID: 70342a1fcdd2
Revises: bd1d7f06da5a
Create Date: 2026-09-25 00:44:52.040763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70342a1fcdd2'
down_revision = 'bd1d7f06da5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offered_condition', sa.String(length=50), server_default='Good', nullable=False))
        batch_op.alter_column('listing_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.alter_column('listing_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('offered_condition')

    # ### end Alembic commands ###
