"""Add password reset fields

Revision ID: 775ceaf41a8e
Revises: 931728661754
Create Date: 2026-09-09 22:15:10.508467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775ceaf41a8e'
down_revision = '931728661754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password_reset_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_reset_expires_at')
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###
