"""Add email verification token fields

Revision ID: 931728661754
Revises: c96a2c37093f
Create Date: 2026-09-05 18:15:48.650658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931728661754'
down_revision = 'c96a2c37093f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_verification_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verification_expires_at')
        batch_op.drop_column('email_verification_token')

    # ### end Alembic commands ###
