"""Add trade receipt tracking

Revision ID: bd1d7f06da5a
Revises: b1122d752d8c
Create Date: 2026-09-24 23:25:22.115829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1d7f06da5a'
down_revision = 'b1122d752d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('listing_id', sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                'sender_received',
                sa.Boolean(),
                server_default=sa.false(),
                nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                'receiver_received',
                sa.Boolean(),
                server_default=sa.false(),
                nullable=False
            )
        )
        batch_op.create_foreign_key(
            'fk_trades_listing_id_listings',
            'listings',
            ['listing_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('receiver_received')
        batch_op.drop_column('sender_received')
        batch_op.drop_column('listing_id')

    # ### end Alembic commands ###
