"""Add email verification status

Revision ID: c96a2c37093f
Revises: d957f9d05c8e
Create Date: 2026-09-05 16:32:38.034993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96a2c37093f'
down_revision = 'd957f9d05c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
            'email_verified',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
